<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-06-20T08:22:42Z" name="DemoQAAutomation" finished-at="2021-06-20T08:22:47Z" duration-ms="5654">
    <groups>
    </groups>
    <test started-at="2021-06-20T08:22:42Z" name="InitialSetup" finished-at="2021-06-20T08:22:42Z" duration-ms="9">
    </test> <!-- InitialSetup -->
    <test started-at="2021-06-20T08:22:42Z" name="Tests" finished-at="2021-06-20T08:22:47Z" duration-ms="5528">
      <class name="setup.SeleniumInit">
        <test-method is-config="true" signature="setup()[pri:0, instance:setup.SeleniumInit@71c8becc]" started-at="2021-06-20T08:22:34Z" name="setup" finished-at="2021-06-20T08:22:42Z" duration-ms="8146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:setup.SeleniumInit@71c8becc]" started-at="2021-06-20T08:22:47Z" name="afterSuite" finished-at="2021-06-20T08:22:49Z" duration-ms="2015" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- setup.SeleniumInit -->
      <class name="runnerClasses.TextBoxRunner">
        <test-method is-config="true" signature="classSetup()[pri:0, instance:runnerClasses.TextBoxRunner@30b7c004]" started-at="2021-06-20T08:22:42Z" name="classSetup" finished-at="2021-06-20T08:22:45Z" duration-ms="3418" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classSetup -->
        <test-method signature="test1()[pri:0, instance:runnerClasses.TextBoxRunner@30b7c004]" started-at="2021-06-20T08:22:45Z" name="test1" finished-at="2021-06-20T08:22:46Z" duration-ms="817" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong Name expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong Name expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at pageObjects.TextBoxPage.verifyData(TextBoxPage.java:58)
at runnerClasses.TextBoxRunner.test1(TextBoxRunner.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
      </class> <!-- runnerClasses.TextBoxRunner -->
    </test> <!-- Tests -->
  </suite> <!-- DemoQAAutomation -->
</testng-results>
